apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: omgcicd
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: omgcicd
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: rootex/my-app:latest
        ports:
        - containerPort: 80
